FROM python:3.12-slim

RUN apt update
RUN apt install python3-pip -y
WORKDIR /app

COPY . .
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


EXPOSE 5000
CMD ["python", "app.py"]
